logging:
  level:
    jdbc:
      audit: 'off'
      connection: 'off'
      resultset: 'off'
      resultsettable: debug
      sqlonly: info
      sqltiming: info

server:
  port: 8084
  

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
spring:
  application:
    name: eureka-client
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: BLOCKLOAD
    url: jdbc:log4jdbc:oracle:thin:@58.151.59.59:21521:ORA11G
    username: BLOCKLOAD

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: /mapper/**/*.xml
  
 